
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/w_sq
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
  timeout: 10000
  host: 127.0.0.1
  port: 6379
  database: 0
  lettuce:
    pool:
      max-active: 1024
      max-wait: 10000
      max-idle: 200
      min-idle: 5


